// Builds js/words.js from:
//  1. The wordle-words npm package (classic NYT list: answers + rest) -> .npmwordle/package/index.mjs
//  2. The tabatkins/wordle-list full allowed-guess list -> .full_words.txt
// Run: node scripts/build-words.mjs
import { readFileSync, writeFileSync } from "node:fs";

const mod = await import("../.npmwordle/package/index.mjs");
const tabatkins = readFileSync(
  new URL("../.full_words.txt", import.meta.url),
  "utf8",
)
  .split(/\r?\n/)
  .filter(Boolean)
  .map((w) => w.trim().toLowerCase());

const answers = [...new Set(mod.answers.map((w) => w.toLowerCase()))].sort();
const guesses = [
  ...new Set([...mod.all, ...tabatkins].map((w) => w.toLowerCase())),
].sort();

const guessSet = new Set(guesses);
for (const a of answers)
  if (!guessSet.has(a)) console.error("answer missing from guesses:", a);

const js = `// Generated by scripts/build-words.mjs — do not edit by hand.
// answers: words NYT has actually used as the puzzle (${answers.length}).
// guesses: every word the NYT Wordle keyboard accepts (${guesses.length}).
window.WORDLE_WORDS = {
  answers: ${JSON.stringify(answers)},
  guesses: ${JSON.stringify(guesses)},
};
`;
writeFileSync(new URL("../js/words.js", import.meta.url), js);
console.log("answers:", answers.length, "guesses:", guesses.length);
